import { TaskItem } from '../types/task';

/**
 * This service is intentionally adapter-based:
 * - Keep compile-safe scaffolding now.
 * - Plug real dart-api calls here once the module is generated by Dart-IDE
 *   and `libs/dart-api` signatures are available.
 */
export class TaskControllerService {
  async getTasksFromController(): Promise<TaskItem[]> {
    // TODO: Replace by real dart-api integration.
    return [
      { id: 'Task_08042026', name: 'Task_08042026' },
      { id: 'Task_08042026_A', name: 'Task_08042026_A' }
    ];
  }

  async playTask(taskName: string): Promise<void> {
    // TODO: Replace by real start task call.
    void taskName;
  }

  async pauseTask(taskName: string): Promise<void> {
    // TODO: Replace by real pause task call.
    void taskName;
  }

  async resumeTask(taskName: string): Promise<void> {
    // TODO: Replace by real resume task call.
    void taskName;
  }

  async stopTask(taskName: string): Promise<void> {
    // TODO: Replace by real stop task call.
    void taskName;
  }
}
